source 'https://rubygems.org'
gem 'github-pages'
gem "jekyll-assets"
gem "uglifier"      # And we want our javascripts to be minified with UglifyJS
gem "sass"          # And we want to write our stylesheets using SCSS/SASS
gem 'therubyracer'
gem 'exifr'
#gem 'rmagick', '~> 2.15', '= 2.15.4' #Forced to this version because 2.16 doesn't work with gallery
gem 'rmagick', '~> 2.15' #Forced to this version because 2.16 doesn't work with gallery
gem 'jekyll-gallery-generator'
gem 'redcarpet'
gem 'jekyll-sitemap'
