source 'https://rubygems.org'
gem 'github-pages'
gem "jekyll-assets"
gem "uglifier"      # And we want our javascripts to be minified with UglifyJS
gem "sass"          # And we want to write our stylesheets using SCSS/SASS
gem 'therubyracer'
gem 'exifr'
gem 'rmagick'
